// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AsyncOperation
    {
        /// <summary>
        /// Initializes a new instance of the AsyncOperation class.
        /// </summary>
        public AsyncOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AsyncOperation class.
        /// </summary>
        public AsyncOperation(string id = default(string), string status = default(string), string reason = default(string))
        {
            Id = id;
            Status = status;
            Reason = reason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

    }
}
