// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Response from the isMinterNFMBRG operation
    /// </summary>
    public partial class IsMinterNFMBRGResponse
    {
        /// <summary>
        /// Initializes a new instance of the IsMinterNFMBRGResponse class.
        /// </summary>
        public IsMinterNFMBRGResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IsMinterNFMBRGResponse class.
        /// </summary>
        public IsMinterNFMBRGResponse(bool? output = default(bool?))
        {
            Output = output;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "output")]
        public bool? Output { get; set; }

    }
}
