// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SafeTransferFromNFMBRGRequest0FunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SafeTransferFromNFMBRGRequest0FunctionParams class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest0FunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SafeTransferFromNFMBRGRequest0FunctionParams class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest0FunctionParams(AccountPartyType fromProperty = default(AccountPartyType), AccountPartyType to = default(AccountPartyType), long? tokenId = default(long?))
        {
            FromProperty = fromProperty;
            To = to;
            TokenId = tokenId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "from")]
        public AccountPartyType FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public AccountPartyType To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenId")]
        public long? TokenId { get; set; }

    }
}
