// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SetApprovalForAllNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SetApprovalForAllNFMBRGRequestFunctionParams class.
        /// </summary>
        public SetApprovalForAllNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SetApprovalForAllNFMBRGRequestFunctionParams class.
        /// </summary>
        public SetApprovalForAllNFMBRGRequestFunctionParams(AccountPartyType to = default(AccountPartyType), bool? approved = default(bool?))
        {
            To = to;
            Approved = approved;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public AccountPartyType To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "approved")]
        public bool? Approved { get; set; }

    }
}
