// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AddMinterNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AddMinterNFMBRGRequestFunctionParams class.
        /// </summary>
        public AddMinterNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// AddMinterNFMBRGRequestFunctionParams class.
        /// </summary>
        public AddMinterNFMBRGRequestFunctionParams(AccountPartyType account = default(AccountPartyType))
        {
            Account = account;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "account")]
        public AccountPartyType Account { get; set; }

    }
}
