// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BurnNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the BurnNFMBRGRequestFunctionParams
        /// class.
        /// </summary>
        public BurnNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BurnNFMBRGRequestFunctionParams
        /// class.
        /// </summary>
        public BurnNFMBRGRequestFunctionParams(long? tokenId = default(long?))
        {
            TokenId = tokenId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokenId")]
        public long? TokenId { get; set; }

    }
}
