// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Request for the Constructor operation
    /// </summary>
    public partial class ConstructorNFMBRGRequest
    {
        /// <summary>
        /// Initializes a new instance of the ConstructorNFMBRGRequest class.
        /// </summary>
        public ConstructorNFMBRGRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConstructorNFMBRGRequest class.
        /// </summary>
        public ConstructorNFMBRGRequest(string callerGroupName = default(string), string callerAccountName = default(string), ConstructorNFMBRGRequestFunctionParams functionParams = default(ConstructorNFMBRGRequestFunctionParams), object additionalMetaData = default(object), string requestId = default(string))
        {
            CallerGroupName = callerGroupName;
            CallerAccountName = callerAccountName;
            FunctionParams = functionParams;
            AdditionalMetaData = additionalMetaData;
            RequestId = requestId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CallerGroupName")]
        public string CallerGroupName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CallerAccountName")]
        public string CallerAccountName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FunctionParams")]
        public ConstructorNFMBRGRequestFunctionParams FunctionParams { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalMetaData")]
        public object AdditionalMetaData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestId")]
        public string RequestId { get; set; }

    }
}
