// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BalanceOfNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// BalanceOfNFMBRGRequestFunctionParams class.
        /// </summary>
        public BalanceOfNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// BalanceOfNFMBRGRequestFunctionParams class.
        /// </summary>
        public BalanceOfNFMBRGRequestFunctionParams(AccountPartyType owner = default(AccountPartyType))
        {
            Owner = owner;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "owner")]
        public AccountPartyType Owner { get; set; }

    }
}
