// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConstructorNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ConstructorNFMBRGRequestFunctionParams class.
        /// </summary>
        public ConstructorNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ConstructorNFMBRGRequestFunctionParams class.
        /// </summary>
        public ConstructorNFMBRGRequestFunctionParams(string name = default(string), string symbol = default(string))
        {
            Name = name;
            Symbol = symbol;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "symbol")]
        public string Symbol { get; set; }

    }
}
