// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SafeTransferFromNFMBRGRequest0
    {
        /// <summary>
        /// Initializes a new instance of the SafeTransferFromNFMBRGRequest0
        /// class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest0()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SafeTransferFromNFMBRGRequest0
        /// class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest0(SafeTransferFromNFMBRGRequest0FunctionParams functionParams = default(SafeTransferFromNFMBRGRequest0FunctionParams))
        {
            FunctionParams = functionParams;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FunctionParams")]
        public SafeTransferFromNFMBRGRequest0FunctionParams FunctionParams { get; set; }

    }
}
