// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SafeTransferFromNFMBRGRequest1
    {
        /// <summary>
        /// Initializes a new instance of the SafeTransferFromNFMBRGRequest1
        /// class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest1()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SafeTransferFromNFMBRGRequest1
        /// class.
        /// </summary>
        public SafeTransferFromNFMBRGRequest1(SafeTransferFromNFMBRGRequest1FunctionParams functionParams = default(SafeTransferFromNFMBRGRequest1FunctionParams))
        {
            FunctionParams = functionParams;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FunctionParams")]
        public SafeTransferFromNFMBRGRequest1FunctionParams FunctionParams { get; set; }

    }
}
