// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.TokenService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SupportsInterfaceNFMBRGRequestFunctionParams
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SupportsInterfaceNFMBRGRequestFunctionParams class.
        /// </summary>
        public SupportsInterfaceNFMBRGRequestFunctionParams()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SupportsInterfaceNFMBRGRequestFunctionParams class.
        /// </summary>
        public SupportsInterfaceNFMBRGRequestFunctionParams(string interfaceId = default(string))
        {
            InterfaceId = interfaceId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "interfaceId")]
        public string InterfaceId { get; set; }

    }
}
